# Generated by Django 3.2.4 on 2022-09-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_nmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='donatenow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ammountvalue', models.CharField(max_length=40)),
                ('Firstname', models.CharField(max_length=40)),
                ('Lastname', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=20)),
            ],
        ),
    ]
