# Generated by Django 3.2.4 on 2022-09-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_donatenow'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatenow',
            name='Occupation',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
