# Generated by Django 3.2.4 on 2022-09-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_nlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donatenow',
            old_name='Ammountvalue',
            new_name='Amountvalue',
        ),
    ]
