# Generated by Django 3.2.4 on 2022-09-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_state_mstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scountry', models.CharField(max_length=30)),
                ('sdate', models.DateField()),
            ],
        ),
    ]
