# Generated by Django 3.2.4 on 2022-09-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='scountry',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='donatenow',
            name='Amountvalue',
            field=models.CharField(max_length=40, null='False'),
        ),
    ]
