# Generated by Django 3.2.4 on 2022-09-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_vgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('des', models.TextField()),
                ('date', models.DateField()),
                ('epic', models.ImageField(null=True, upload_to='ststic/event/')),
            ],
        ),
    ]
