# Generated by Django 3.2.4 on 2022-09-08 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event',
        ),
    ]
