# Generated by Django 3.2.4 on 2022-09-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='epic',
            field=models.ImageField(null=True, upload_to='static/event/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='ppic',
            field=models.ImageField(null=True, upload_to='static/profile/'),
        ),
    ]
