# Generated by Django 3.2.4 on 2022-09-10 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20220908_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nlogin',
        ),
    ]
