# Generated by Django 3.2.4 on 2022-09-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_delete_nlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatenow',
            name='ppic',
            field=models.ImageField(null=True, upload_to='static/payss'),
        ),
    ]
