# Generated by Django 3.2.4 on 2022-09-10 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_donatenow_ppic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donatenow',
            old_name='ppic',
            new_name='Payss',
        ),
    ]
