# Generated by Django 3.2.4 on 2022-09-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_rename_ppic_donatenow_payss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donatenow',
            old_name='Payss',
            new_name='Paypic',
        ),
    ]
