# Generated by Django 3.2.4 on 2022-09-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_rename_payss_donatenow_paypic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatenow',
            name='Paypic',
        ),
        migrations.AddField(
            model_name='donatenow',
            name='ppic',
            field=models.ImageField(null=True, upload_to='static/profileS/'),
        ),
    ]
