# Generated by Django 3.2.4 on 2022-09-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20220914_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatenow',
            name='ppic',
        ),
        migrations.AddField(
            model_name='donatenow',
            name='Paypic',
            field=models.ImageField(null=True, upload_to='static/Paytm/'),
        ),
    ]
